### ISSUE TITLE
Async Read Exception: 104, Connection reset by peer

### ISSUE THREAD

**Issue by cookerrr** [tixi/Domoticz-Tuya-SmartBulb-Plugin#1]
I'm not sure if its something on my end, or if the plugin just needs updated, but this error keeps coming up in my domoticz log every few minutes...

Async Read Exception: 104, Connection reset by peer

I'm assuming it has to do with the heartbeat, where its keeps the connection alive.  Are you still using this plugin, or is there some better way to control these bulbs?   I notice it seems to lag domoticz when it goes through the error cycle.  Other than that the plugin does work to control the bulbs.  I would edit myself, but it just seems above my knowledge when I look at the plugin code.

**Comment by tixi** [comment]
It happen when the hearbeat is to long for the device. you can reduce it to 2 for instance just with the line:
__HB_BASE_FREQ = 2 #instead of 6

**Comment by cookerrr** [comment]
I actually stumble upon that difference in this plugin vs. your plug plugin and made that change last night, the errors are gone since the change, thanks!

**Comment by v0d0r** [comment]
I am running into a similar issue. Intermittent tuya Async Read Exception: 104, Connection reset by peer. I tried the __HB_BASE_FREQ = 2 #instead of 6 without any luck.  Something else interesting I discovered. After disabling the plugin in domoticz and using tuya-cli I immediately get a response via tuya-cli. Re-enable the domoticz plugin then I get no connection from tuya-cli. Almost like the domoticz plugin makes a connection and holds it open thereby taking up the single allowed connection except it does not control the smart bulb at all.  
Any suggestions what else to try?

## snip from tuya-cli ##
tuya-cli get --ip 192.168.128.21 --id 82504753cc50e3146d08 --key ****************** -a
{ devId: '82504753cc50e3146d08',
  dps:
   { '1': true,
##################

**Comment by COLOC-BOB** [comment]
bonjour, 
Je viens d'associer un interrupteur wifi acheté avec Ali qui fonctionne avec SMARTLIFE. 
Il y a en 1 que je n'ai pas mis à jour et fonctionne très bien avec DZ 
J'en ai 3 avec le dernier firmware WIFI et MCU 1.1.5 et j'ai maintenant cette erreur sur ces périphériques: 
Async Read Exception: 104, connexion réinitialisée par un pair

**Comment by Adam-1969** [comment]
Hi Tixi,
I have a Tuya bulb but a version without RGB. I connected it through the method of commandline to find the keys.
Problem is that the bulb does not respond to commands and i hav the obove mentioned " Async Read Exception: 104, Connection reset by peer" error.  It looks like there is communication with the bulb when debug is on.
Hope you can help me, thanks in advance
